### ISSUE TITLE
get primary group?

### ISSUE THREAD

**Issue by z1haze** [romanbican/roles#109]
Is there anyway to set a 'primary' group and just retrieve that?

**Comment by z1haze** [comment]
And not completely related, but how do you retrieve the role name for the user? Right now I am doing 

 public function roles()
    {
        return $this->belongsToMany('Bican\Roles\Models\Role');
    }

and something like $user->roles[0]->i want the rolename but i dont know to get it :)

**Comment by arafatx** [comment]
I think you might need another field to mark a primary group because this package doesn't have this method of setting primary group.

1) add another field call 'primary_role' in either your users database or roles database,

2) add function call setPrimaryRole($adminGroup) and getPrimaryRole() to mark and retrieve the primary group from the field primary_role. 

$user1->attachRole ($adminGroup) //user1 is assigned as adminGroup
$user1->attachRole($managerGroup) //user1 is also assigned as managerGroup

$user1->setPrimaryRole($managerGroup) //set user1 primary group as managerGroup

$user1->getPrimaryRole(); //retrieve what is the primary group for this $user1. This returns $managerGroup.

As I said,  Perhaps there is a better way of doing this.
