### ISSUE TITLE
Documentation needs to be updated

### ISSUE THREAD

**Issue by Lyca0n** [romanbican/roles#177]
there are some parts in the documentation that need to be updated as for laravel 5.2
 as class User does not extend Model in the default setup it extends Authenticatable.

**Comment by Isfirs** [comment]
I want to point you to this quote: 
`Powerful package for handling roles and permissions in Laravel 5 (5.1 and also 5.0)`

As for, there is no need for a 5.2 documentation since this package first needs a fork/update to L5.2.
And here it seems like everyone feels responsible to fork/PR only that piece of functionality that they needed and doesn't work. Maybe someone should make a L5.2 fork and branch it into the repo.
