### ISSUE TITLE
connection setting not necessary

### ISSUE THREAD

**Issue by jonjonw** [romanbican/roles#75]
I don't think the connection setting (https://github.com/romanbican/roles/blob/master/src/config/roles.php#L16) and associated code in the Traits in necessary. You can simply set the connection on the Role and Permission models.

If you handle it this way then you can replace some of the custom queries with eloquent calls which would make it easier for people who rename the tables/fields in the database.

ex:
```
class SomeModel extends Eloquent {

    protected $connection = 'mysql2';

}
```

See:
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Eloquent/Model.php#L40

**Comment by romanbican** [comment]
I don't undestand. Connection setting is here if you want a different connection for `Role` and `Permission` models. But if you want default connection, you just leave it like that. As far as I know, there is no code in traits because of that, only in models.

https://github.com/romanbican/roles/blob/master/src/Bican/Roles/Models/Permission.php#L31
https://github.com/romanbican/roles/blob/master/src/Bican/Roles/Models/Role.php#L31

**Comment by sniper7kills** [comment]
@romanbican, there is one spot where this configuration is being used.
`$prefix = config('database.connections.' . config('database.default') . '.prefix');` 
within the HasRoleAndPermission Trait, getRolePermissions() fucntion.
