### ISSUE TITLE
Check for allowed permission for entity showing unexpected results

### ISSUE THREAD

**Issue by thril** [romanbican/roles#87]
I got some unexpected results when using the `allowed()` method. I was using the blade directive to determine if the current user could modify the user being viewed. To my surprise, user A was able to see the "edit" link for user B, but shouldn't be able to.

Upon inspecting the `allowed()` method, I feel like it's not returning the correct value when the `$owner` is `true`. This is the existing code:

```php
if ($owner === true && $entity->{$ownerColumn} == $this->id) {
    return true;
}
```

But I think it should probably be:

```php
if ($owner === true) {
    return ($entity->{$ownerColumn} == $this->id);
}
```

My assumption is that if `$owner` is set, then we always want to compare based off that and ignore the subsequent check to `isAllowed()`. Can you set me straight here? Thanks!

**Comment by romanbican** [comment]
If it is not working, you must provide more information.

But it should be working as we expect. If user is a owner, then return true. But if not, we still want to check if he or she has a permission. We don't want to skip that.

**Comment by thril** [comment]
It may be working as intended, but my comment is that it's not working as I would have expected.  From the scenario I pointed out above, I don't want `User A` to be able to modify `User B`, so I restrict it by checking that the entity being modified is the same as the authenticated user. But the `allowed()` method basically says, "Okay I know you're checking the entity as the owner, but I'm just gonna go ahead and check to see if the authenticated user has any of the permissions being checked and not consider the model being checked." To me, that doesn't seem right.

So let's say `allowed()` is as intended, how would one run the check below?

```php
// User A viewing User B
if (Auth::check() && Auth::user()->can('user.update') && Auth::user()->id == $user->id) {
   // show edit link
}
```

I would expect the following to work, but it doesn't because it always shows the link when the user has the `user.update` permission, even if they are not the owner of the record.

```php
@allowed('user.update', $user, true, 'id')
    // show edit link
@endallowed
```

Thanks for checking.

**Comment by aronduby** [comment]
I'm just some random dude who stopped in to ask about something else, so take this as such...

It sounds like you have an AND understanding while the `allowed` function has an OR understanding. You are looking for if the user has `user.update` permission _AND_ is the owner. The allowed method looks at if the user has the permission _OR_ is the owner. For all the applications I've worked on the OR method works much better because it easily allows the owner or an admin to edit something.

Specific to your implementation, I would probably take the custom check you wrote and pass that in as a variable to the view, like `$edit` and use that in an if statement instead of the `@allowed`.
